apiVersion: v1
kind: ConfigMap
metadata:
  name: peo-config
  namespace: peo-platform
data:
  # Endpoints para comunicacao interna
  ENDPOINTS_IDENTITY: "http://peo-identity-api:80/"
  ENDPOINTS_GESTAOCONTEUDO: "http://peo-gestaoconteudo-api:80/"
  ENDPOINTS_GESTAOALUNOS: "http://peo-gestaoalunos-api:80/"
  ENDPOINTS_FATURAMENTO: "http://peo-faturamento-api:80/"
  
  # Configuracoes JWT
  JWT_ISSUER_IDENTITY: "https://peo-identity-api/"
  JWT_ISSUER_GESTAOCONTEUDO: "https://peo-gestaoconteudo-api/"
  JWT_ISSUER_GESTAOALUNOS: "https://peo-gestaoalunos-api/"
  JWT_ISSUER_FATURAMENTO: "https://peo-faturamento-api/"
  JWT_ISSUER_BFF: "https://peo-bff/"
  
  JWT_AUDIENCE_IDENTITY: "https://peo-identity-api/"
  JWT_AUDIENCE_GESTAOCONTEUDO: "https://peo-gestaoconteudo-api/"
  JWT_AUDIENCE_GESTAOALUNOS: "https://peo-gestaoalunos-api/"
  JWT_AUDIENCE_FATURAMENTO: "https://peo-faturamento-api/"
  JWT_AUDIENCE_BFF: "https://peo-bff/"
  
  # Config CORS para BFF
  CORS_ALLOWED_ORIGINS_0: "http://localhost:30000"
  CORS_ALLOWED_ORIGINS_1: "http://peo-frontend"
  
  # Configuracoes de ambiente
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:80"