---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: peo-gestaoconteudo-api
  namespace: peo-platform
  labels:
    app: peo-gestaoconteudo-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peo-gestaoconteudo-api
  template:
    metadata:
      labels:
        app: peo-gestaoconteudo-api
    spec:
      containers:
      - name: gestaoconteudo-api
        image: peo-gestaoconteudo-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: peo-config
              key: ASPNETCORE_ENVIRONMENT
        - name: ASPNETCORE_URLS
          valueFrom:
            configMapKeyRef:
              name: peo-config
              key: ASPNETCORE_URLS
        - name: ConnectionStrings__SqlServerConnection
          value: "Server=peo-sqlserver;Database=PeoGestaoConteudo;User Id=sa;Password=$(SA_PASSWORD);TrustServerCertificate=true;"
        - name: ConnectionStrings__messaging
          value: "amqp://$(RABBITMQ_USER):$(RABBITMQ_PASSWORD)@peo-rabbitmq:5672/"
        - name: SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: peo-secrets
              key: SA_PASSWORD
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: peo-secrets
              key: RABBITMQ_USER
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: peo-secrets
              key: RABBITMQ_PASSWORD
        - name: Jwt__Key
          valueFrom:
            secretKeyRef:
              name: peo-secrets
              key: JWT_KEY
        - name: Jwt__Issuer
          valueFrom:
            configMapKeyRef:
              name: peo-config
              key: JWT_ISSUER_GESTAOCONTEUDO
        - name: Jwt__Audience
          valueFrom:
            configMapKeyRef:
              name: peo-config
              key: JWT_AUDIENCE_GESTAOCONTEUDO
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"


---
apiVersion: v1
kind: Service
metadata:
  name: peo-gestaoconteudo-api
  namespace: peo-platform
  labels:
    app: peo-gestaoconteudo-api
spec:
  selector:
    app: peo-gestaoconteudo-api
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP