apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: peo-platform

resources:
  - base/namespace.yaml
  - base/secrets.yaml
  - base/configmap.yaml
  - infrastructure/sqlserver.yaml
  - infrastructure/rabbitmq.yaml
  - microservices/identity-api.yaml
  - microservices/gestaoconteudo-api.yaml
  - microservices/gestaoalunos-api.yaml
  - microservices/faturamento-api.yaml
  - frontend/bff.yaml
  - frontend/spa.yaml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/name: peo-platform
      app.kubernetes.io/version: "1.1.0"
      app.kubernetes.io/component: microservices
      app.kubernetes.io/part-of: peo-platform

images:
  - name: peo-identity-api
    newTag: latest
  - name: peo-gestaoconteudo-api
    newTag: latest
  - name: peo-gestaoalunos-api
    newTag: latest
  - name: peo-faturamento-api
    newTag: latest
  - name: peo-bff
    newTag: latest
  - name: peo-frontend
    newTag: latest