name: CI/CD Pipeline - .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true

jobs:
  
  build:
    name: Build with WarnAsError
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore 
    - name: Build
      run: dotnet build --no-restore -WarnAsError


  build-test-sonarqube:
    name: Build, Test and SonarQube
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x' 

      - name: Cache SonarQube
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add scanner to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: SonarQube Begin
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          dotnet sonarscanner begin \
            /k:"jonataspc_MBA-Peo-microservices" \
            /o:"jonataspc" \
            /d:sonar.host.url="$SONAR_HOST_URL" \
            /d:sonar.login="$SONAR_TOKEN" \
            /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Debug --no-restore

      # - name: Install dotCover
      #   run: dotnet tool install --global JetBrains.dotCover.CommandLineTools --version 2025.1.5
        
      # - name: Test + code coverage
      #   run: dotCover cover-dotnet --output report.html --ReportType HTML --Filters="+:module=Peo.*" -- test 

      # - name: Archive code coverage results
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: code-coverage-report
      #     path: |
      #         report/**/*
      #         report.html

      - name: Test with coverage
        run: |
          dotnet test \
            --no-build \
            --configuration Debug \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults/coverage.opencover.xml \
            /p:CoverletOutputFormat=opencover

      - name: SonarQube End
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner end \
            /d:sonar.login="$SONAR_TOKEN"
